import type { Database } from '../types/database.types';
type Brand = Database['public']['Tables']['brands']['Row'];
type Category = Database['public']['Tables']['categories']['Row'];
type Subcategory = Database['public']['Tables']['subcategories']['Row'];
type Color = Database['public']['Tables']['colors']['Row'];
type Material = Database['public']['Tables']['materials']['Row'];
type ProductImage = Database['public']['Tables']['product_images']['Row'];
type Tag = Database['public']['Tables']['tags']['Row'];
export interface ProductoCompleto {
    id: string;
    nombre: string;
    descripcion: string | null;
    sku: string;
    slug: string;
    precio: number;
    precio_anterior: number | null;
    precio_metro: number | null;
    stock: number | null;
    unidad: string | null;
    medidas: string | null;
    metros_por_caja: number | null;
    moneda: string | null;
    pei: string | null;
    activo: boolean | null;
    disponible: boolean | null;
    nuevo: boolean | null;
    en_oferta: boolean | null;
    destacado: boolean | null;
    created_at: string | null;
    updated_at: string | null;
    fecha_creacion: string | null;
    fecha_actualizacion: string | null;
    brand_id: string | null;
    color_id: string | null;
    material_id: string | null;
    brand?: Brand;
    color?: Color;
    material?: Material;
    images: ProductImage[];
    categories: Category[];
    subcategories: Subcategory[];
    tags: Tag[];
}
export interface ProductoAPI {
    id: string;
    nombre: string;
    descripcion: string | null;
    marca: string;
    categoria: string[];
    subcategoria?: string;
    precio: number;
    precioMetro: number | null;
    precioAnterior: number | null;
    metrosPorCaja: number | null;
    stock: number | null;
    unidad: string | null;
    medidas: string | null;
    color?: string;
    pei?: string | null;
    imagenPrincipal?: string;
    disponible: boolean;
    activo: boolean;
    nuevo: boolean;
    enOferta: boolean;
    slug: string;
    tags: string[];
    destacado: boolean;
}
export declare const useProductsStore: import("pinia").StoreDefinition<"products", Pick<{
    productos: import("vue").Ref<{
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[], ProductoCompleto[] | {
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[]>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    initialized: import("vue").Ref<boolean, boolean>;
    brands: import("vue").Ref<{
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    categories: import("vue").Ref<{
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    subcategories: import("vue").Ref<{
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    colors: import("vue").Ref<{
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    materials: import("vue").Ref<{
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    tags: import("vue").Ref<{
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    productosActivos: import("vue").ComputedRef<{
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[]>;
    productosFormateados: import("vue").ComputedRef<ProductoAPI[]>;
    productosActivosFormateados: import("vue").ComputedRef<ProductoAPI[]>;
    cargarProductos: (forzar?: boolean) => Promise<void>;
    cargarReferencias: () => Promise<void>;
    getProductoBySlug: (slug: string) => ProductoCompleto | undefined;
    getProductosByCategoria: (categoria: string) => ProductoCompleto[];
    getProductosBySubcategoria: (subcategoria: string) => ProductoCompleto[];
    getProductosByMarca: (marca: string) => ProductoCompleto[];
    getProductosByTag: (tag: string) => ProductoCompleto[];
    getProductosDestacados: () => ProductoCompleto[];
    getProductosNuevos: () => ProductoCompleto[];
    getProductosEnOferta: () => ProductoCompleto[];
    buscarProductos: (termino: string) => ProductoCompleto[];
    getProductoBySlugFormateado: (slug: string) => ProductoAPI | undefined;
    getProductosByCategoriaFormateado: (categoria: string) => ProductoAPI[];
    transformarProducto: (producto: ProductoCompleto) => ProductoAPI;
}, "categories" | "subcategories" | "tags" | "brands" | "colors" | "materials" | "productos" | "loading" | "error" | "initialized">, Pick<{
    productos: import("vue").Ref<{
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[], ProductoCompleto[] | {
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[]>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    initialized: import("vue").Ref<boolean, boolean>;
    brands: import("vue").Ref<{
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    categories: import("vue").Ref<{
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    subcategories: import("vue").Ref<{
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    colors: import("vue").Ref<{
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    materials: import("vue").Ref<{
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    tags: import("vue").Ref<{
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    productosActivos: import("vue").ComputedRef<{
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[]>;
    productosFormateados: import("vue").ComputedRef<ProductoAPI[]>;
    productosActivosFormateados: import("vue").ComputedRef<ProductoAPI[]>;
    cargarProductos: (forzar?: boolean) => Promise<void>;
    cargarReferencias: () => Promise<void>;
    getProductoBySlug: (slug: string) => ProductoCompleto | undefined;
    getProductosByCategoria: (categoria: string) => ProductoCompleto[];
    getProductosBySubcategoria: (subcategoria: string) => ProductoCompleto[];
    getProductosByMarca: (marca: string) => ProductoCompleto[];
    getProductosByTag: (tag: string) => ProductoCompleto[];
    getProductosDestacados: () => ProductoCompleto[];
    getProductosNuevos: () => ProductoCompleto[];
    getProductosEnOferta: () => ProductoCompleto[];
    buscarProductos: (termino: string) => ProductoCompleto[];
    getProductoBySlugFormateado: (slug: string) => ProductoAPI | undefined;
    getProductosByCategoriaFormateado: (categoria: string) => ProductoAPI[];
    transformarProducto: (producto: ProductoCompleto) => ProductoAPI;
}, "productosActivos" | "productosFormateados" | "productosActivosFormateados">, Pick<{
    productos: import("vue").Ref<{
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[], ProductoCompleto[] | {
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[]>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    initialized: import("vue").Ref<boolean, boolean>;
    brands: import("vue").Ref<{
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        created_at: string | null;
        description: string | null;
        id: string;
        is_active: boolean | null;
        logo_url: string | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    categories: import("vue").Ref<{
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        created_at: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    subcategories: import("vue").Ref<{
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[], {
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[] | {
        category_id: string;
        created_at: string | null;
        description: string | null;
        display_order: number | null;
        id: string;
        image_url: string | null;
        is_active: boolean | null;
        name: string;
        slug: string;
        updated_at: string | null;
    }[]>;
    colors: import("vue").Ref<{
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        hex_code: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    materials: import("vue").Ref<{
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    tags: import("vue").Ref<{
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[], {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[] | {
        created_at: string | null;
        id: string;
        name: string;
        slug: string;
    }[]>;
    productosActivos: import("vue").ComputedRef<{
        id: string;
        nombre: string;
        descripcion: string | null;
        sku: string;
        slug: string;
        precio: number;
        precio_anterior: number | null;
        precio_metro: number | null;
        stock: number | null;
        unidad: string | null;
        medidas: string | null;
        metros_por_caja: number | null;
        moneda: string | null;
        pei: string | null;
        activo: boolean | null;
        disponible: boolean | null;
        nuevo: boolean | null;
        en_oferta: boolean | null;
        destacado: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        fecha_creacion: string | null;
        fecha_actualizacion: string | null;
        brand_id: string | null;
        color_id: string | null;
        material_id: string | null;
        brand?: {
            created_at: string | null;
            description: string | null;
            id: string;
            is_active: boolean | null;
            logo_url: string | null;
            name: string;
            slug: string;
            updated_at: string | null;
        } | undefined;
        color?: {
            created_at: string | null;
            hex_code: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        material?: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        } | undefined;
        images: {
            alt_text: string | null;
            created_at: string | null;
            display_order: number | null;
            id: string;
            is_primary: boolean | null;
            product_id: string;
            url: string;
        }[];
        categories: {
            created_at: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        subcategories: {
            category_id: string;
            created_at: string | null;
            description: string | null;
            display_order: number | null;
            id: string;
            image_url: string | null;
            is_active: boolean | null;
            name: string;
            slug: string;
            updated_at: string | null;
        }[];
        tags: {
            created_at: string | null;
            id: string;
            name: string;
            slug: string;
        }[];
    }[]>;
    productosFormateados: import("vue").ComputedRef<ProductoAPI[]>;
    productosActivosFormateados: import("vue").ComputedRef<ProductoAPI[]>;
    cargarProductos: (forzar?: boolean) => Promise<void>;
    cargarReferencias: () => Promise<void>;
    getProductoBySlug: (slug: string) => ProductoCompleto | undefined;
    getProductosByCategoria: (categoria: string) => ProductoCompleto[];
    getProductosBySubcategoria: (subcategoria: string) => ProductoCompleto[];
    getProductosByMarca: (marca: string) => ProductoCompleto[];
    getProductosByTag: (tag: string) => ProductoCompleto[];
    getProductosDestacados: () => ProductoCompleto[];
    getProductosNuevos: () => ProductoCompleto[];
    getProductosEnOferta: () => ProductoCompleto[];
    buscarProductos: (termino: string) => ProductoCompleto[];
    getProductoBySlugFormateado: (slug: string) => ProductoAPI | undefined;
    getProductosByCategoriaFormateado: (categoria: string) => ProductoAPI[];
    transformarProducto: (producto: ProductoCompleto) => ProductoAPI;
}, "cargarProductos" | "cargarReferencias" | "getProductoBySlug" | "getProductosByCategoria" | "getProductosBySubcategoria" | "getProductosByMarca" | "getProductosByTag" | "getProductosDestacados" | "getProductosNuevos" | "getProductosEnOferta" | "buscarProductos" | "getProductoBySlugFormateado" | "getProductosByCategoriaFormateado" | "transformarProducto">>;
export {};
